apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: postgres
resources:
  - pv-postgres.yaml
  - pvc-postgres.yaml
  - cm-postgres.yaml
  - secret-postgres.yaml
  - deployment-postgres.yaml
  - service-postgres.yaml
