apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  datasource:
    name: pv-postgres
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
